using MpesaLib.Interfaces;
using MpesaLib.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MpesaLib.Clients
{
    /// <summary>
    /// Instantiate this class to check Mpesa Account balance
    /// </summary>
    public class AccountBalanceQueryClient : IAccountBalanceQueryClient
    {
        private readonly HttpClient _httpClient;

        /// <summary>

        /// Queries Mpesa Account Balance

        /// </summary>
        /// <param name="httpClient"></param>
        public AccountBalanceQueryClient(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        /// <summary>
        /// Defaults to sandbox URL. Override with Mpesa production url when deploying to a production environment.
        /// </summary>
        public string BaseUri { get; set; } = "https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query";

        /// <summary>
        /// Make an Account balance query request
        /// </summary>
        /// <param name="accbalance">Account balance query request object</param>
        /// <param name="accesstoken">Access token generated by AuthClient</param>
        /// <returns>Returns a JSON string that you should deserialize</returns>
        public async Task<string> GetBalance(AccountBalance accbalance, string accesstoken)
        {
            Uri BaseAddress = new Uri(BaseUri);
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",accesstoken);                   

            var values = new Dictionary<string, string>
            {
                { "Initiator", accbalance.Initiator },
                { "SecurityCredential", accbalance.SecurityCredential},
                { "CommandID", accbalance.CommandID},
                { "PartyA", accbalance.PartyA},
                { "IdentifierType", accbalance.IdentifierType},
                { "Remarks", accbalance.Remarks },
                { "QueueTimeOutURL", accbalance.QueueTimeOutURL},
                { "ResultURL", accbalance.ResultURL}
            };

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, BaseAddress)
            {
                Content = new StringContent(JsonConvert.SerializeObject(values).ToString(), Encoding.UTF8, "application/json")
            };


            HttpResponseMessage response = await _httpClient.SendAsync(request);

            return response.Content.ReadAsStringAsync().Result;
        }
    }
}
