using MpesaLib.Interfaces;
using MpesaLib.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MpesaLib.Clients
{
    /// <summary>
    /// Instantiate this class to make a Mpesa Transaction status api call
    /// </summary>
    public class TransactionStatusClient : ITransactionStatusClient
    {
       
        private readonly HttpClient _httpclient;
        /// <summary>
        /// Queries status of Mpesa transactions
        /// </summary>
        /// <param name="httpClient"></param>
        public TransactionStatusClient(HttpClient httpClient)
        {
            _httpclient = httpClient;
        }

        /// <summary>
        /// Defaults to sandbox URL. Override with Mpesa production url when deploying to a production environment.
        /// </summary>
        public string BaseUri { get; set; } = "https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query";

        /// <summary>
        /// Query Mpesa transaction status
        /// </summary>
        /// <param name="transactionStatus">Transaction status request object</param>
        /// <param name="accesstoken">Access token generated by AuthClient</param>
        /// <returns>
        /// Returns a JSON string that you should deserialize
        /// </returns>
        public async Task<string> GetTransactionStatus(MpesaTransactionStatus transactionStatus, string accesstoken)
        {
            
            Uri BaseAddress = new Uri(BaseUri);
            _httpclient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _httpclient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accesstoken);

            var values = new Dictionary<string, string>
            {
                {"Initiator", transactionStatus.Initiator },
                {"SecurityCredential", transactionStatus.SecurityCredential },
                {"CommandID", transactionStatus.CommandID },
                {"TransactionID", transactionStatus.TransactionID },
                {"PartyA", transactionStatus.PartyA },
                {"IdentifierType", transactionStatus.IdentifierType },
                {"ResultURL", transactionStatus.ResultURL },
                {"QueueTimeOutURL", transactionStatus.QueueTimeOutURL },
                {"Remarks", transactionStatus.Remarks },
                { "Occasion", transactionStatus.Occasion }

            };

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, BaseAddress)
            {
                Content = new StringContent(JsonConvert.SerializeObject(values).ToString(), Encoding.UTF8, "application/json")
            };


            HttpResponseMessage response = await _httpclient.SendAsync(request);

            return response.Content.ReadAsStringAsync().Result;
        }
    }
}
