using MpesaLib.Interfaces;
using MpesaLib.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MpesaLib.Clients
{
    /// <summary>
    /// Instantiate this class to make a Mpesa Transaction Reversal API call.
    /// </summary>
    public class TransactionReversalClient : ITransactionReversalClient
    {
        private readonly HttpClient _httpclient;
        /// <summary>
        /// Reverses Mpesa transactions
        /// </summary>
        /// <param name="httpClient"></param>
        public TransactionReversalClient(HttpClient httpClient)
        {
            _httpclient = httpClient;
        }

        /// <summary>
        /// Defaults to sandbox URL. Override with Mpesa production url when deploying to a production environment.
        /// </summary>
        public string BaseUri { get; set; } = "https://sandbox.safaricom.co.ke/mpesa/reversal/v1/request";

        /// <summary>
        /// Reverse Mpesa transaction
        /// </summary>
        /// <param name="reversal">Mpesa Reversal request object</param>
        /// <param name="accesstoken">Access token generated by AuthClient</param>
        /// <returns>Returns a JSON string that you should deserialize</returns>
        public async Task<string> ReverseTransaction(Reversal reversal, string accesstoken)
        {
            Uri BaseAddress = new Uri(BaseUri);
            _httpclient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _httpclient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accesstoken);            

            var values = new Dictionary<string, string>
            {
                {"Initiator", reversal.Initiator },
                {"SecurityCredential", reversal.SecurityCredential },
                {"CommandID", reversal.CommandID },
                {"TransactionID", reversal.TransactionID },
                {"Amount", reversal.Amount },
                {"ReceiverParty", reversal.ReceiverParty },
                {"RecieverIdentifierType", reversal.RecieverIdentifierType },
                {"ResultURL", reversal.ResultURL },
                {"QueueTimeOutURL", reversal.QueueTimeOutURL },
                {"Remarks", reversal.Remarks },
                { "Occasion", reversal.Occasion }

            };

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, BaseAddress)
            {
                Content = new StringContent(JsonConvert.SerializeObject(values).ToString(), Encoding.UTF8, "application/json")
            };

            HttpResponseMessage response = await _httpclient.SendAsync(request);

            return response.Content.ReadAsStringAsync().Result;
        }
    }
}
